[DEFAULT]
debug = true
verbose = true

# Use the rabbitmq container defined in docker-compose
transport_url = rabbit://guest:guest@rabbitmq:5672/
messaging_transport_url = rabbit://guest:guest@rabbitmq:5672/

providers = coriolis.providers.vmware.exp.VMwareVSphereExportProvider,coriolis.providers.olvm.imp.OLVMoVirtImportProvider

# ========== Database ==========
[database]
# Use the database container defined in docker-compose
connection = mysql+pymysql://coriolis:coriolis_password@database/coriolis?charset=utf8

# ========== API ==========
[api]
api_migration_listen = 0.0.0.0
api_migration_listen_port = 7667
api_migration_workers = 1
worker_count = 1


# ========== Concurrency ==========
[oslo_concurrency]
lock_path = /tmp

# ========== VMware ==========
[vmware]
worker_ip = 172.23.219.54
worker_ssh_password = VMware.99




